<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="26" passed="15" failed="9" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-16T12:43:51 IDT" name="All Test Suite" finished-at="2021-08-16T12:45:00 IDT" duration-ms="68866">
    <groups>
    </groups>
    <test started-at="2021-08-16T12:43:51 IDT" name="C:/Users/Alqarout/IdeaProjects/FirstSeleniumTask-FirstFunctionality" finished-at="2021-08-16T12:44:18 IDT" duration-ms="26838">
      <class name="main.java.MainPageTest">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:main.java.MainPageTest@446293d]" started-at="2021-08-16T12:43:51 IDT" name="beforeClass" finished-at="2021-08-16T12:43:55 IDT" duration-ms="4048" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="testMainPageTitle()[pri:0, instance:main.java.MainPageTest@446293d]" started-at="2021-08-16T12:43:55 IDT" name="testMainPageTitle" finished-at="2021-08-16T12:43:55 IDT" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMainPageTitle -->
        <test-method signature="testMainPageHeaders()[pri:0, instance:main.java.MainPageTest@446293d]" started-at="2021-08-16T12:43:55 IDT" name="testMainPageHeaders" finished-at="2021-08-16T12:43:55 IDT" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMainPageHeaders -->
        <test-method signature="clickHomeButton()[pri:0, instance:main.java.MainPageTest@446293d]" started-at="2021-08-16T12:43:55 IDT" name="clickHomeButton" finished-at="2021-08-16T12:43:56 IDT" duration-ms="161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickHomeButton -->
        <test-method signature="clickLoginButton()[pri:0, instance:main.java.MainPageTest@446293d]" started-at="2021-08-16T12:43:56 IDT" name="clickLoginButton" finished-at="2021-08-16T12:43:56 IDT" duration-ms="58" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Address Book - Sign In] but found [Address Book]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Address Book - Sign In] but found [Address Book]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at main.java.MainPageTest.clickLoginButton(MainPageTest.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickLoginButton -->
      </class> <!-- main.java.MainPageTest -->
      <class name="main.java.SignInPageTest">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:43:56 IDT" name="beforeClass" finished-at="2021-08-16T12:43:57 IDT" duration-ms="1719" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:43:57 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:13 IDT" duration-ms="15796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testSignInPageTitle()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:13 IDT" name="testSignInPageTitle" finished-at="2021-08-16T12:44:13 IDT" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSignInPageTitle -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:13 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:13 IDT" duration-ms="273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testSignInPageElementsExist()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:13 IDT" name="testSignInPageElementsExist" finished-at="2021-08-16T12:44:14 IDT" duration-ms="133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSignInPageElementsExist -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:14 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:14 IDT" duration-ms="243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testBadCredentialsInForm()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:14 IDT" name="testBadCredentialsInForm" finished-at="2021-08-16T12:44:16 IDT" duration-ms="2486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBadCredentialsInForm -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:16 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:17 IDT" duration-ms="245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="clickSignUpButton()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:17 IDT" name="clickSignUpButton" finished-at="2021-08-16T12:44:17 IDT" duration-ms="516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickSignUpButton -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:17 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:17 IDT" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signIn()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:17 IDT" name="signIn" finished-at="2021-08-16T12:44:18 IDT" duration-ms="688" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:main.java.SignInPageTest@2df9b86]" started-at="2021-08-16T12:44:18 IDT" name="afterClass" finished-at="2021-08-16T12:44:18 IDT" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- main.java.SignInPageTest -->
    </test> <!-- C:/Users/Alqarout/IdeaProjects/FirstSeleniumTask-FirstFunctionality -->
    <test started-at="2021-08-16T12:43:51 IDT" name="C:/Users/Alqarout/IdeaProjects/FirstSeleniumTask-SecondFunctionality" finished-at="2021-08-16T12:45:00 IDT" duration-ms="68866">
      <class name="main.java.AfterSignInTest">
        <test-method is-config="true" signature="ChromeDriverInitialize()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:43:51 IDT" name="ChromeDriverInitialize" finished-at="2021-08-16T12:43:51 IDT" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ChromeDriverInitialize -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:43:51 IDT" name="beforeClass" finished-at="2021-08-16T12:44:20 IDT" duration-ms="28969" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:20 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:21 IDT" duration-ms="356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validateMainContents()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:21 IDT" name="validateMainContents" finished-at="2021-08-16T12:44:21 IDT" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateMainContents -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:21 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:21 IDT" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testAddressBtn()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:21 IDT" name="testAddressBtn" finished-at="2021-08-16T12:44:22 IDT" duration-ms="580" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddressBtn -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:22 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:22 IDT" duration-ms="378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createEmptyAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:22 IDT" name="createEmptyAddress" finished-at="2021-08-16T12:44:23 IDT" duration-ms="569" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://a.testaddressbook.com/addresses/new] but found [http://a.testaddressbook.com/addresses]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://a.testaddressbook.com/addresses/new] but found [http://a.testaddressbook.com/addresses]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at main.java.AfterSignInTest.createEmptyAddress(AfterSignInTest.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEmptyAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:23 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:23 IDT" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createInvalidFirstNameAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:23 IDT" name="createInvalidFirstNameAddress" finished-at="2021-08-16T12:44:27 IDT" duration-ms="4258" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at main.java.AfterSignInTest.createInvalidFirstNameAddress(AfterSignInTest.java:167)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createInvalidFirstNameAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:27 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:27 IDT" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createInvalidLastNameAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:27 IDT" name="createInvalidLastNameAddress" finished-at="2021-08-16T12:44:32 IDT" duration-ms="4279" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at main.java.AfterSignInTest.createInvalidLastNameAddress(AfterSignInTest.java:178)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createInvalidLastNameAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:32 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:32 IDT" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createInvalidZipCodeAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:32 IDT" name="createInvalidZipCodeAddress" finished-at="2021-08-16T12:44:36 IDT" duration-ms="4208" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at main.java.AfterSignInTest.createInvalidZipCodeAddress(AfterSignInTest.java:190)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createInvalidZipCodeAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:36 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:36 IDT" duration-ms="236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createInvalidAgeAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:36 IDT" name="createInvalidAgeAddress" finished-at="2021-08-16T12:44:41 IDT" duration-ms="4344" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at main.java.AfterSignInTest.createInvalidAgeAddress(AfterSignInTest.java:215)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createInvalidAgeAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:41 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:41 IDT" duration-ms="246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createInvalidBirthdayAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:41 IDT" name="createInvalidBirthdayAddress" finished-at="2021-08-16T12:44:45 IDT" duration-ms="4316" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at main.java.AfterSignInTest.createInvalidBirthdayAddress(AfterSignInTest.java:248)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createInvalidBirthdayAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:45 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:45 IDT" duration-ms="236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createValidAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:45 IDT" name="createValidAddress" finished-at="2021-08-16T12:44:47 IDT" duration-ms="1267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createValidAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:47 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:47 IDT" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="editAddressCorrectlyAfterCreation()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:47 IDT" name="editAddressCorrectlyAfterCreation" finished-at="2021-08-16T12:44:50 IDT" duration-ms="3074" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editAddressCorrectlyAfterCreation -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:50 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:50 IDT" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="editAddressIncorrectlyAfterCreation()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:50 IDT" name="editAddressIncorrectlyAfterCreation" finished-at="2021-08-16T12:44:53 IDT" duration-ms="2989" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://a.testaddressbook.com/addresses/8770] but found [http://a.testaddressbook.com/addresses/8770/edit]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://a.testaddressbook.com/addresses/8770] but found [http://a.testaddressbook.com/addresses/8770/edit]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at main.java.AfterSignInTest.editAddressIncorrectlyAfterCreation(AfterSignInTest.java:300)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editAddressIncorrectlyAfterCreation -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:53 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:53 IDT" duration-ms="273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="listAddressAfterCreation()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:53 IDT" name="listAddressAfterCreation" finished-at="2021-08-16T12:44:56 IDT" duration-ms="2669" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listAddressAfterCreation -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:56 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:56 IDT" duration-ms="258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="listAddressBeforeCreation()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:56 IDT" name="listAddressBeforeCreation" finished-at="2021-08-16T12:44:58 IDT" duration-ms="1327" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listAddressBeforeCreation -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:58 IDT" name="beforeMethod" finished-at="2021-08-16T12:44:58 IDT" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="destroyAddress()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:58 IDT" name="destroyAddress" finished-at="2021-08-16T12:44:59 IDT" duration-ms="1366" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at main.java.AfterSignInTest.destroyAddress(AfterSignInTest.java:339)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroyAddress -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:44:59 IDT" name="beforeMethod" finished-at="2021-08-16T12:45:00 IDT" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signOut()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:45:00 IDT" name="signOut" finished-at="2021-08-16T12:45:00 IDT" duration-ms="464" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOut -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:main.java.AfterSignInTest@e15b7e8]" started-at="2021-08-16T12:45:00 IDT" name="afterClass" finished-at="2021-08-16T12:45:00 IDT" duration-ms="49" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- main.java.AfterSignInTest -->
    </test> <!-- C:/Users/Alqarout/IdeaProjects/FirstSeleniumTask-SecondFunctionality -->
  </suite> <!-- All Test Suite -->
</testng-results>
